/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS app_settings(id SERIAL PRIMARY KEY NOT NULL, display_name character varying(255) NULL, name character varying(255) NULL, value character varying(255) NULL, created_by character varying(255) NULL, created_date timestamp with time zone NULL, modified_date_time timestamp with time zone NULL, last_modified_by character varying(255) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS app_settings_pkey ON hrms.app_settings USING btree (id);
