/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS basic_skill(id SERIAL PRIMARY KEY NOT NULL, skill character varying(100) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_24990_id_unique ON hrms.basic_skill USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_24990_primary ON hrms.basic_skill USING btree (id);
