/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS columnmap(id SERIAL PRIMARY KEY NOT NULL, etl_id integer REFERENCES etl_metadata(id) NULL, is_enabled boolean NULL, is_quotes_required boolean NULL, is_unique boolean NULL, local_column character varying(255) NULL, qb_column character varying(255) NULL, qb_column_id integer NULL);
CREATE INDEX IF NOT EXISTS idx_25008_fk_columnmap_to_etl_metapoagh ON hrms.columnmap USING btree (etl_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25008_primary ON hrms.columnmap USING btree (id);
