/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS country_and_state(id SERIAL PRIMARY KEY NOT NULL, country character varying(200) NOT NULL, state character varying(200) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25032_id_unique ON hrms.country_and_state USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25032_primary ON hrms.country_and_state USING btree (id);
