/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS document_type(id SERIAL PRIMARY KEY NOT NULL, document_type character varying(50) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25047_id_unique ON hrms.document_type USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25047_primary ON hrms.document_type USING btree (id);
