/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS email_template(id SERIAL PRIMARY KEY NOT NULL, template_content text NULL, created_by character varying(45) NULL, created_date date NULL, last_modified_by character varying(45) NULL, last_modified_date date NULL, mail_to character varying(45) NULL, mail_from character varying(45) NULL, template_name character varying(200) NULL, template_subject character varying(200) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25062_id_unique ON hrms.email_template USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25062_primary ON hrms.email_template USING btree (id);
