/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS etl_sync_to_qb_meta(id integer PRIMARY KEY NOT NULL, sync_action character varying(100) NULL, sync_sub_action character varying(100) NULL, sync_order integer NULL, qb_db_name character varying(100) NULL, qb_action_api character varying(100) NULL, hrms_view_name character varying(100) NULL, is_enabled boolean NULL DEFAULT true , created_at timestamp with time zone NULL, updated_at timestamp with time zone NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25085_primary ON hrms.etl_sync_to_qb_meta USING btree (id);
