/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS etl_sync_to_qb_field_mappings(id integer PRIMARY KEY NOT NULL, etl_sync_to_qb_meta integer NULL, qb_field_name character varying(150) NULL, view_column_name character varying(150) NULL, is_enabled boolean NULL DEFAULT true , created_at timestamp with time zone NULL, updated_at timestamp with time zone NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25081_primary ON hrms.etl_sync_to_qb_field_mappings USING btree (id);
