/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS etl_metadata(id SERIAL PRIMARY KEY NOT NULL, is_delete_allowed boolean NULL, is_enabled boolean NULL, is_insert_allowed boolean NULL, is_modify_allowed boolean NULL, local_table_name character varying(255) NULL, local_unique_column character varying(255) NULL, modified_epoch bigint NULL, qb_column_list character varying(255) NULL, qb_table_name character varying(255) NULL, modified_date_time timestamp with time zone NULL, qb_app_token character varying(255) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25074_primary ON hrms.etl_metadata USING btree (id);
