/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS hr_comments(id SERIAL PRIMARY KEY NOT NULL, comments character varying(45) NULL, hr_name character varying(45) NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL, comment_flag boolean NULL, user_id integer REFERENCES user(id) NOT NULL, send_flag boolean NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25094_id_unique ON hrms.hr_comments USING btree (id);
CREATE INDEX IF NOT EXISTS idx_25094_fk_hr_comments_user1 ON hrms.hr_comments USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25094_primary ON hrms.hr_comments USING btree (id);
