/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS medical_and_accidental_coverage(id SERIAL PRIMARY KEY NOT NULL, date_of_submission date NOT NULL, employee_name character varying(50) NOT NULL, place character varying(50) NOT NULL, voluntary_top_up boolean NOT NULL, user_id integer REFERENCES user(id) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL, topup_insurance character varying(45) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25130_id_unique ON hrms.medical_and_accidental_coverage USING btree (id);
CREATE INDEX IF NOT EXISTS idx_25130_fk_medical_and_accidental_coverage_user1 ON hrms.medical_and_accidental_coverage USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25130_primary ON hrms.medical_and_accidental_coverage USING btree (id);
