/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS personal_ids(id SERIAL PRIMARY KEY NOT NULL, name_as_per_bank character varying(100) NULL, account_number character varying(50) NULL, branch_name character varying(100) NULL, ifsc_code character varying(50) NULL, universal_account_number character varying(50) NULL, pan_card_name character varying(50) NULL, permanent_account_number character varying(50) NULL, passport_name character varying(50) NULL, passport_number character varying(50) NULL, date_of_issue date NULL, date_of_expiry date NULL, place_of_issue character varying(50) NULL, aadhar_name character varying(50) NULL, aadhar_card_number character varying(50) NULL, user_id integer REFERENCES user(id) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL, name_as_per_uan character varying(50) NULL, name_of_bank character varying(50) NULL, name_of_the_bank character varying(50) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25166_user_id_unique ON hrms.personal_ids USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25166_id_unique ON hrms.personal_ids USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25166_primary ON hrms.personal_ids USING btree (id);
