/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS qb_ldap_status(id SERIAL PRIMARY KEY NOT NULL, user_id integer UNIQUE NOT NULL, employee_table_rid integer NULL, private_table_rid integer NULL, secure_table_rid integer NULL, benefit_table_rid integer NULL, resume_table_rid integer NULL, prior_organization_table_rid integer NULL, education_table_rid integer NULL, employee_id integer NULL, employee_mail_id character varying(255) NULL, ldap_status boolean NOT NULL, created_by character varying(255) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(255) NOT NULL, last_modified_date timestamp with time zone NOT NULL, performance_info_rid integer NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "UK_qb_ldap_status_user_id" ON hrms.qb_ldap_status USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS qb_ldap_status_pkey ON hrms.qb_ldap_status USING btree (id);
