/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS role(id SERIAL PRIMARY KEY NOT NULL, role character varying(50) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25181_id_unique ON hrms.role USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25181_primary ON hrms.role USING btree (id);
