/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS table35(id SERIAL PRIMARY KEY NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25194_primary ON hrms.table35 USING btree (id);
