/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS university_details(id SERIAL PRIMARY KEY NOT NULL, degree character varying(150) NULL, course_type character varying(150) NULL, college_name character varying(100) NULL, affiliating_university character varying(150) NULL, year_of_study_start_year date NULL, year_of_study_end_year date NULL, cgpa character varying(45) NULL, university_outof character varying(45) NULL, user_id integer REFERENCES user(id) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL, degree_other character varying(45) NULL, couse_type_other character varying(45) NULL, discipline_major character varying(500) NULL, discipline_other character varying(255) NULL, is_pg boolean NULL DEFAULT false , discipline_major_text character varying(255) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25200_id_unique ON hrms.university_details USING btree (id);
CREATE INDEX IF NOT EXISTS idx_25200_fk_university_details_user1 ON hrms.university_details USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25200_primary ON hrms.university_details USING btree (id);
