/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS user_upload_files(id SERIAL PRIMARY KEY NOT NULL, document_name character varying(2000) NOT NULL, key character varying(2000) NOT NULL, path character varying(2000) NOT NULL, document_type_id integer REFERENCES document_type(id) NOT NULL, user_id integer REFERENCES user(id) NOT NULL, created_by character varying(45) NOT NULL, last_modified_by character varying(45) NOT NULL, entity character varying(45) NULL, entity_id integer NULL, file_base64_format character varying NULL, created_date timestamp with time zone NULL, last_modified_date timestamp with time zone NULL, file_type character varying(2000) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25255_id_unique ON hrms.user_upload_files USING btree (id);
CREATE INDEX IF NOT EXISTS idx_25255_fk_user_upload_files_user1 ON hrms.user_upload_files USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_25255_fk_user_upload_files_document_type1 ON hrms.user_upload_files USING btree (document_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25255_primary ON hrms.user_upload_files USING btree (id);
