/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS user_review_details(id integer NULL, first_name character varying(50) NULL, designation character varying(50) NULL, expected_joining_date date NULL, joining_location character varying(50) NULL, business_unit character varying(50) NULL, manager_name character varying(50) NULL, review_by character varying(45) NULL, joining_status character varying(45) NULL, review_status character varying(45) NULL, comments character varying(45) NULL, created_date timestamp with time zone NULL, user_id integer NULL, rnk bigint NULL);
