/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS user_test(id SERIAL PRIMARY KEY NOT NULL, first_name character varying(255) NULL, last_name character varying(255) NULL, qb_id integer NULL, skills_bucket character varying(255) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25246_primary ON hrms.user_test USING btree (id);
