/*
2020-01-21 15:06:16.122965: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS visa_details(id SERIAL PRIMARY KEY NOT NULL, country character varying(100) NULL, visa_type character varying(200) NULL, date_of_expiry date NULL, user_id integer REFERENCES user(id) NOT NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL, visa_details_other character varying(45) NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25264_id_unique ON hrms.visa_details USING btree (id);
CREATE INDEX IF NOT EXISTS idx_25264_fk_visa_details_user1 ON hrms.visa_details USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25264_primary ON hrms.visa_details USING btree (id);
