/*
05:58:47.532029: Auto generated by get_table_ddl API v1
*/
CREATE TABLE IF NOT EXISTS work_experience(id SERIAL PRIMARY KEY NOT NULL, total_experience_years integer NULL, total_experience_months integer NULL, relevant_experience_years integer NULL, relevant_experience_months integer NULL, user_id integer REFERENCES user(id) NOT NULL, im_fresher boolean NULL, created_by character varying(45) NOT NULL, created_date timestamp with time zone NOT NULL, last_modified_by character varying(45) NOT NULL, last_modified_date timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25276_user_id_unique ON hrms.work_experience USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25276_id_unique ON hrms.work_experience USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_25276_primary ON hrms.work_experience USING btree (id);
