/*
2020-01-21 15:06:16.122965: Auto generated by get_function_ddl API v1
*/
CREATE OR REPLACE FUNCTION get_tables_ddl(vschema character varying, vtime boolean DEFAULT false)
RETURNS TABLE(tname text, result text) AS $$ 
BEGIN  
   RETURN query     
        SELECT table_name, get_table_ddl(table_name, vtime) FROM (SELECT table_name::text FROM INFORMATION_SCHEMA.TABLES WHERE table_schema = vschema)t;  
END;
$$ LANGUAGE plpgsql;