/*
05:58:47.532029: Auto generated by get_function_ddl API v1
*/
CREATE OR REPLACE FUNCTION get_function_ddl(vschema character varying, vtime boolean DEFAULT false)
RETURNS TABLE(func_name text, result text) AS $$
BEGIN
RETURN query
    SELECT 
        f_name::text, E'/*\n'||CASE WHEN vtime THEN NOW()::time::text||':' ELSE ' ' END||E' Auto generated by get_function_ddl API v1\n*/\nCREATE OR REPLACE FUNCTION '||f_name||'('||
        f_arg||E')\nRETURNS '||f_result||' AS '||CHR(36)||CHR(36)||f_desc||CHR(36)||CHR(36)||' LANGUAGE plpgsql;'
    FROM
        (SELECT 
            pp.proname AS f_name, 
            pg_get_function_arguments(pp.oid) AS f_arg, 
            pg_get_function_result(pp.oid) AS f_result, 
            pp.prosrc AS f_desc 
        FROM pg_catalog.pg_proc pp
        LEFT JOIN pg_catalog.pg_namespace pn ON pn.oid = pp.pronamespace     
        WHERE pg_catalog.pg_function_is_visible(pp.oid) AND pn.nspname  = vschema)
    t;
END;
$$ LANGUAGE plpgsql;