/*
2020-01-21 15:06:16.122965: Auto generated by get_function_ddl API v1
*/
CREATE OR REPLACE FUNCTION get_table_ddl(vtable text, vtime boolean DEFAULT false)
RETURNS TABLE(t_row text) AS $$
BEGIN
RETURN query
    SELECT E'/*\n'||CASE WHEN vtime THEN NOW() AT TIME ZONE 'Asia/Kolkata'::text||':' ELSE '' END||E' Auto generated by get_table_ddl API v1\n*/\n'||'CREATE TABLE IF NOT EXISTS '||vtable||'('||array_to_string(array_agg(column_name||' '||datatype||' '||CASE WHEN pk_count = 1 OR contype != 'PRIMARY KEY '  THEN contype ELSE '' END||ref||nullable||defval),', ')||CASE WHEN AVG(pk_count) > 1 THEN ', PRIMARY KEY('||array_to_string(array_agg(CASE WHEN contype IS NOT NULL THEN column_name END),', ')||')' ELSE '' END||');' FROM
    (SELECT
        DISTINCT pat.attname AS column_name,
        COUNT(CASE WHEN inf.constraint_type = 'PRIMARY KEY' THEN inf.constraint_type END) OVER(PARTITION BY inf.constraint_type) AS pk_count,
        CASE
            WHEN (SELECT * FROM pg_get_serial_sequence(pcl.relname, pat.attname)) IS NOT NULL THEN 'SERIAL'  
            ELSE pg_catalog.format_type(pat.atttypid, pat.atttypmod)
        END AS datatype,
        CASE 
            WHEN inf.constraint_type IS NULL THEN NULL
            ELSE CONCAT(inf.constraint_type,' ')
        END AS contype,
        CASE 
            WHEN tc.constraint_type = 'FOREIGN KEY' THEN 'REFERENCES '||ccu.table_name||'('||ccu.column_name||') '
            ELSE ''
        END AS ref,
        CASE
            WHEN pat.attnotnull THEN 'NOT NULL'
            ELSE 'NULL'
        END AS nullable,
        CASE
            WHEN isc.column_default IS NULL THEN ''
            WHEN (SELECT * FROM pg_get_serial_sequence(isc.table_name, isc.column_name)) IS NOT NULL THEN '' 
            ELSE ' DEFAULT '||isc.column_default||' '
        END AS defval,
        pat.attnum AS columns_number
    FROM pg_class pcl INNER JOIN pg_attribute pat ON pcl.oid = pat.attrelid
    INNER JOIN INFORMATION_SCHEMA.COLUMNS isc ON isc.column_name = pat.attname
    LEFT JOIN pg_constraint pct ON pat.attrelid = pct.conrelid AND pat.attnum = ANY(pct.conkey) AND pct.contype != 'f'
    LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS inf ON pct.conname = inf.constraint_name 
    LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ck ON isc.column_name = ck.column_name AND isc.table_name = ck.table_name AND ck.position_in_unique_constraint = 1
    LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ON ck.table_name = tc.table_name AND ck.constraint_name = tc.constraint_name
    LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.constraint_name = ccu.constraint_name
    WHERE pcl.relname = vtable AND isc.table_name = vtable AND pat.attnum > 0 AND pat.attisdropped = 'f'
    ORDER BY pat.attnum)t;
RETURN query
    SELECT REPLACE(indexdef, 'INDEX', 'INDEX IF NOT EXISTS')||';' FROM pg_indexes WHERE tablename = vtable;
END;
$$ LANGUAGE plpgsql;