/*
05:58:47.532029: Auto generated by get_function_ddl API v1
*/
CREATE OR REPLACE FUNCTION on_update_current_timestamp_created_date()
RETURNS trigger AS $$
BEGIN
  NEW.created_date = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;