/*
2020-01-21 15:06:16.122965: Auto generated by get_function_ddl API v1
*/
CREATE OR REPLACE FUNCTION on_update_current_timestamp_created_date()
RETURNS trigger AS $$
BEGIN
  NEW.created_date = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;