/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_app_settings_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON app_settings
 FOR EACH ROW
EXECUTE PROCEDURE aud_app_settings_trigger_fn();
