/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_business_unit_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON business_unit
 FOR EACH ROW
EXECUTE PROCEDURE aud_business_unit_trigger_fn();
