/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_certification_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON certification
 FOR EACH ROW
EXECUTE PROCEDURE aud_certification_trigger_fn();
