/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_columnmap_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON columnmap
 FOR EACH ROW
EXECUTE PROCEDURE aud_columnmap_trigger_fn();
