/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_common_mail_ids_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON common_mail_ids
 FOR EACH ROW
EXECUTE PROCEDURE aud_common_mail_ids_trigger_fn();
