/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_country_and_state_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON country_and_state
 FOR EACH ROW
EXECUTE PROCEDURE aud_country_and_state_trigger_fn();
