/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_declaration_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON declaration
 FOR EACH ROW
EXECUTE PROCEDURE aud_declaration_trigger_fn();
