/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_document_type_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON document_type
 FOR EACH ROW
EXECUTE PROCEDURE aud_document_type_trigger_fn();
