/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_email_template_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON email_template
 FOR EACH ROW
EXECUTE PROCEDURE aud_email_template_trigger_fn();
