/*
2020-01-21 15:06:16.122965: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_employee_details_vw_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON employee_details_vw
 FOR EACH ROW
EXECUTE PROCEDURE aud_employee_details_vw_trigger_fn();
