/*
2020-01-21 15:06:16.122965: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_etl_lookup_sync_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON etl_lookup_sync
 FOR EACH ROW
EXECUTE PROCEDURE aud_etl_lookup_sync_trigger_fn();
