/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_etl_sync_to_qb_meta_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON etl_sync_to_qb_meta
 FOR EACH ROW
EXECUTE PROCEDURE aud_etl_sync_to_qb_meta_trigger_fn();
