/*
2020-01-21 15:06:16.122965: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_internal_user_role_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON internal_user_role
 FOR EACH ROW
EXECUTE PROCEDURE aud_internal_user_role_trigger_fn();
