/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_internal_user_role_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON internal_user_role
 FOR EACH ROW
EXECUTE PROCEDURE aud_internal_user_role_trigger_fn();
