/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_lta_form_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON lta_form
 FOR EACH ROW
EXECUTE PROCEDURE aud_lta_form_trigger_fn();
