/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_medical_and_accidental_coverage_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON medical_and_accidental_coverage
 FOR EACH ROW
EXECUTE PROCEDURE aud_medical_and_accidental_coverage_trigger_fn();
