/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_personal_ids_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON personal_ids
 FOR EACH ROW
EXECUTE PROCEDURE aud_personal_ids_trigger_fn();
