/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_reference_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON reference
 FOR EACH ROW
EXECUTE PROCEDURE aud_reference_trigger_fn();
