/*
2020-01-21 15:06:16.122965: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_table33_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON table33
 FOR EACH ROW
EXECUTE PROCEDURE aud_table33_trigger_fn();

CREATE trigger on_update_current_timestamp
BEFORE UPDATE
ON table33
 FOR EACH ROW
EXECUTE PROCEDURE on_update_current_timestamp_updated_at();
