/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_visa_details_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON visa_details
 FOR EACH ROW
EXECUTE PROCEDURE aud_visa_details_trigger_fn();
