/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_work_history_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON work_history
 FOR EACH ROW
EXECUTE PROCEDURE aud_work_history_trigger_fn();
