/*
05:58:47.532029: Auto generated by get_trigger_ddl API v1
*/
CREATE trigger hrms_work_experience_aud_trig
BEFORE INSERT OR DELETE OR UPDATE
ON work_experience
 FOR EACH ROW
EXECUTE PROCEDURE aud_work_experience_trigger_fn();
